const LOCAL_RESPONSES = [
    {
        category: "identidad",
keywords: [
    "quien es jorge",
    "quien es jorge patricio",
    "quien es santamaria",
    "quien es santamaria cherrez",
    "presentame a jorge",
    "hablame de el",

    "perfil",
    "perfil de",
    "perfil profesional de jorge",
    "perfil profesional",
    

    "habla de jorge",
    "habla acerca de jorge",
    "habla sobre jorge",
    "sobre jorge",
    "dime sobre jorge",
    "cuentame sobre Jorge",
    "cuentame acerca de Jorge",
    "cuentame de Jorge",
    "quiero saber de Jorge",
    "acerca de jorge",
    "hablame de el",
    "hablame acerca de el",
    "hablame sobre el",
    "dime sobre el",
    "dime acerca de el",
    "cuentame acerca de el",
    "cuentame sobre el",
    "cuentame de el",
    "habla sobre el",
    "habla acerca de el",
    "hablame",
    "cuentame",
],
        responses: [
            "Jorge Patricio Santamaría Cherrez es ingeniero en sistemas y tiene un máster en ingeniería de software. Su experiencia se enfoca en desarrollo Full Stack, virtualización y ciberseguridad, trabajando con React, JavaScript, Django, Java y SQL.",
            "Jorge Patricio Santamaría Cherrez es un profesional de Ingeniería de Software, con formación en Ingeniería en Sistemas y un Máster en esta área.",
            "Jorge es Ingeniero en Sistemas y cuenta con un Máster en Ingeniería de Software. Se especializa en desarrollo Full Stack, además de tener conocimientos en virtualización y ciberseguridad. Ha creado aplicaciones web, un chatbot, un juego de ajedrez y un e-commerce.",
            "Jorge es Ingeniero en Sistemas por la Universidad Indoamérica y Máster en Ingeniería de Software y Sistemas Informáticos por la UNIR.",
            "Jorge Patricio es un profesional de sistemas con formación de máster en ingeniería de software. Entre sus principales áreas están el desarrollo Full Stack, la ciberseguridad y la virtualización, utilizando tecnologías como React, Django, JavaScript y Java.",
            "Jorge Santamaría Cherrez es Ingeniero en Sistemas y Máster en Ingeniería de Software. Ha trabajado en diferentes proyectos tecnológicos, incluyendo aplicaciones React, un quiz sobre Ecuador, una aplicación del clima, un chatbot, ajedrez y una tienda online.",
            "Jorge se desempeña como Ingeniero de Software y Desarrollador Full Stack. Tiene formación en Ingeniería de Sistemas y una maestría en Ingeniería de Software, con experiencia en tecnologías como React, JavaScript, Django, Java y bases de datos SQL.",
            "Jorge Patricio Santamaría Cherrez combina su formación en Ingeniería de Sistemas con un máster en Ingeniería de Software. Sus principales áreas de interés son el desarrollo Full Stack, la virtualización y la ciberseguridad, donde trabaja con diferentes tecnologías web.",
            "Jorge es un Ingeniero en Sistemas con Máster en Ingeniería de Software. Dentro de su experiencia destacan el desarrollo de aplicaciones web y proyectos Full Stack, utilizando herramientas como React, Django, JavaScript, Java y bases de datos SQL.",
            "Jorge Patricio tiene formación como Ingeniero en Sistemas y Máster en Ingeniería de Software. En su trayectoria ha desarrollado proyectos como un portfolio, un quiz sobre Ecuador, una app del clima, un chatbot, un juego de ajedrez y un e-commerce.",
            "Jorge Santamaría se especializa en desarrollo de software y Full Stack. Es Ingeniero en Sistemas y tiene un Máster en Ingeniería de Software, con conocimientos en React, JavaScript, Django, Java, SQL, virtualización y ciberseguridad.",
"Jorge Patricio Santamaría Cherrez es un profesional de software con formación en Ingeniería de Sistemas y una maestría en Ingeniería de Software. Ha desarrollado diversos proyectos web y aplicaciones, destacando su trabajo con React, Django, JavaScript, Java y SQL.",
        ],
    },

            {
    category: "formacion",
    keywords: [
        "donde estudio",
        "en que universidad",
        "donde estudia",
        "en que universidades estudio",
        "universidad de jorge",
        "universidades de jorge",
        "donde hizo sus estudios",
        "donde realizo sus estudios",
        "donde se formo",
        "donde curso sus estudios",
    ],
    responses: [
        "Jorge estudió Ingeniería en Sistemas en la Universidad Indoamérica, Ecuador. Posteriormente realizó un Máster en Ingeniería de Software y Sistemas Informáticos en la UNIR, España.",
        "Su formación universitaria comenzó con Ingeniería en Sistemas en la Universidad Indoamérica y continuó con un Máster en Ingeniería de Software y Sistemas Informáticos en la UNIR.",
        "Jorge cursó Ingeniería en Sistemas en Ecuador y posteriormente realizó un Máster en Ingeniería de Software y Sistemas Informáticos en España.",
        "A nivel universitario, Jorge estudió Ingeniería en Sistemas en la Universidad Indoamérica y después realizó un Máster en Ingeniería de Software y Sistemas Informáticos en la UNIR.",
        "Jorge realizó sus estudios de Ingeniería en Sistemas en la Universidad Indoamérica y su formación de posgrado en la UNIR, España.",
        "En cuanto a sus estudios universitarios, Jorge se formó en la Universidad Indoamérica y posteriormente continuó sus estudios en la UNIR.",
        "Jorge estudió su carrera de Ingeniería en Sistemas en Ecuador y realizó su Máster en Ingeniería de Software y Sistemas Informáticos en España.",
        "Su trayectoria universitaria comprende estudios en la Universidad Indoamérica y posteriormente en la Universidad Internacional de La Rioja, UNIR.",
        "Jorge inició su formación profesional en la Universidad Indoamérica y continuó su especialización académica en la UNIR, España.",
        "Las universidades donde Jorge realizó sus principales estudios son la Universidad Indoamérica, en Ecuador, y la UNIR, en España.",
    ],
},

{
    category: "formacion",
  keywords: [
    "ingenieria de",
    "que ingenieria hizo",
    "que ingenieria estudio",
    "que ingenieria tiene",
    "titulo de ingenieria",
      "su ingenieria",
      
    "es ingeniero",
    "estudio ingenieria",
    "carrera de ingenieria",

    "donde estudio su ingenieria",
    "donde estudio la ingenieria",
    "donde estudio ingenieria",

      "donde siguio su ingenieria",
    "donde  siguio la ingenieria",
    "donde siguio ingenieria",

    "donde hizo su ingenieria",
    "donde hizo la ingenieria",
    "donde hizo ingenieria",

    "donde realizo su ingenieria",
    "donde realizo la ingenieria",
    "donde realizo ingenieria",

    "donde curso su ingenieria",
    "donde curso la ingenieria",
    "donde curso ingenieria",

    "en que universidad estudio su ingenieria",
    "en que universidad hizo su ingenieria",
    "en que universidad estudio ingenieria",
    "universidad de su ingenieria",
    "universidad de la ingenieria",
],
    responses: [
        "Jorge estudió Ingeniería en Sistemas en la Universidad Indoamérica, Ecuador.",
        "La carrera universitaria de Jorge es Ingeniería en Sistemas y siguió la minsma en la Universidad Indoamerica.",
        "Jorge es Ingeniero en Sistemas, titulado por la Universidad Indoamérica.",
        "Su formación de grado corresponde a Ingeniería en Sistemas en la Universidad Indoamérica, Ecuador.",
        "Jorge realizó sus estudios universitarios en Ingeniería en Sistemas en la Universidad Indoamerica.",
        "A nivel de grado, Jorge estudió Ingeniería en Sistemas en Ecuador.",
        "Jorge cuenta con el título de Ingeniero en Sistemas por la Universidad Indoamérica.",
        "La carrera que estudió Jorge fue Ingeniería en Sistemas en la Universidad Indoamérica.",
        "Jorge se formó profesionalmente como Ingeniero en Sistemas.",
        "Su carrera universitaria principal es Ingeniería en Sistemas, cursada en la Universidad Indoamérica.",
    ],
},

{
    category: "formacion",
    keywords: [
    "master",
    "maestria",
    "posgrado",

    "que master tiene",
    "que maestria tiene",
    "que posgrado tiene",

    "donde estudio su master",
    "donde estudio su maestria",
    "donde estudio su posgrado",

    "donde estudio el master",
    "donde estudio la maestria",
    "donde estudio el posgrado",

    "donde hizo su master",
    "donde hizo su maestria",
    "donde hizo su posgrado",

    "donde realizo su master",
    "donde realizo su maestria",
    "donde realizo su posgrado",

    "estudio una maestria",
    "tiene maestria",
    "tiene un master",
    "master de jorge",
],
    responses: [
        "Jorge realizó un Máster en Ingeniería de Software y Sistemas Informáticos en la Universidad Internacional de La Rioja (UNIR), España.",
        "Jorge tiene un Máster en Ingeniería de Software y Sistemas Informáticos realizado en la UNIR.",
        "A nivel de posgrado, Jorge cuenta con un Máster en Ingeniería de Software y Sistemas Informáticos por la UNIR, España.",
        "Jorge continuó su formación con un Máster en Ingeniería de Software y Sistemas Informáticos en la Universidad Internacional de La Rioja.",
        "La maestría de Jorge es en Ingeniería de Software y Sistemas Informáticos, realizada en la UNIR.",
        "Jorge realizó sus estudios de posgrado en Ingeniería de Software y Sistemas Informáticos en España.",
        "Su formación de posgrado corresponde a un Máster en Ingeniería de Software y Sistemas Informáticos por la UNIR.",
        "Jorge cuenta con una maestría especializada en Ingeniería de Software y Sistemas Informáticos.",
        "Después de su Ingeniería en Sistemas, Jorge continuó sus estudios con un Máster en la UNIR, España.",
        "Jorge se especializó mediante un Máster en Ingeniería de Software y Sistemas Informáticos en la Universidad Internacional de La Rioja.",
    ],
},

{
    category: "formacion",
    keywords: [
        "formacion de jorge",
        "formacion",
        "educacion",
        "formacion academica",
        "educacion de jorge",
        "trayectoria academica",
        "estudios de jorge",
        "estudios academicos",
        "perfil academico",
        "historial academico",
        "preparacion academica",
        "nivel academico",
    ],
    responses: [
        "La formación académica de Jorge incluye Ingeniería en Sistemas por la Universidad Indoamérica y un Máster en Ingeniería de Software y Sistemas Informáticos por la UNIR, España.",
        "Jorge tiene formación de grado en Ingeniería en Sistemas y formación de posgrado en Ingeniería de Software y Sistemas Informáticos.",
        "Su trayectoria académica comprende una Ingeniería en Sistemas en Ecuador y un Máster en Ingeniería de Software y Sistemas Informáticos en España.",
        "En cuanto a formación académica, Jorge cuenta con una Ingeniería en Sistemas y posteriormente realizó un Máster especializado en Ingeniería de Software y Sistemas Informáticos.",
        "Jorge es Ingeniero en Sistemas y cuenta además con un Máster en Ingeniería de Software y Sistemas Informáticos.",
        "Su formación combina estudios de Ingeniería en Sistemas en Ecuador y estudios de posgrado en España.",
        "La trayectoria académica de Jorge comenzó con Ingeniería en Sistemas y continuó con un Máster en Ingeniería de Software y Sistemas Informáticos.",
        "Jorge cuenta con formación universitaria y de posgrado orientada al área de sistemas e ingeniería de software.",
        "Su preparación académica incluye Ingeniería en Sistemas por la Universidad Indoamérica y un Máster realizado en la UNIR.",
        "En resumen, Jorge tiene una Ingeniería en Sistemas y un Máster en Ingeniería de Software y Sistemas Informáticos.",
    ],
},

{
    category: "notas",
    keywords: [
        "promedio ingenieria",
        "nota ingenieria",
        "promedio universidad",
        "nota universidad",
        "promedio de ingenieria",
        "promedio de la ingenieria",
        "nota de ingenieria",
        "nota de la ingenieria",
        "calificacion ingenieria",
        "nota de su ingenieria",
        "promedio de la ingenieria",
"promedio de su ingenieria",
        "calificacion de la ingenieria",
        "calificacion de su ingenieria",
    ],
    responses: [
        "Jorge obtuvo un promedio de 9 en Ingeniería en Sistemas.",
        "En Ingeniería en Sistemas, Jorge obtuvo un promedio final de 9.",
        "La nota promedio de Jorge en Ingeniería en Sistemas fue de 9.",
        "Jorge terminó su Ingeniería en Sistemas con un promedio de 9.",
        "Jorge obtuvo una calificación promedio de 9 durante su Ingeniería en Sistemas.",
        "El promedio final de Jorge en su Ingeniería en Sistemas fue de 9 sobre 10.",
        "En sus estudios de Ingeniería en Sistemas, Jorge alcanzó un promedio de 9.",
        "Jorge obtuvo 9 de promedio en su carrera de Ingeniería en Sistemas.",
        "Su promedio universitario en Ingeniería en Sistemas fue de 9.",
        "La Ingeniería en Sistemas de Jorge tuvo un promedio final de 9 sobre 10.",
    ],
},


{
    category: "notas",
    keywords: [
        "promedio master",
        "promedio de su master",
        "nota master",
        "promedio posgrado",
        "nota posgrado",
        "promedio maestria",
        "nota maestria",
        "promedio del master",
        "nota del master",
        "promedio de la maestria",
        "calificacion master",
        "nota de Master",
        "nota de su master",
        "nota de su maestria",
        "nota de maestria",
        "nota de la maestria",
        "nota de su posgrado",
        "nota del posgrado",
        "nota del master",
    ],
    responses: [
        "Jorge obtuvo un promedio de 8.68 en el Máster en Ingeniería de Software y Sistemas Informáticos.",
        "En su Máster, Jorge obtuvo un promedio de 8.68.",
        "La media final de Jorge en el Máster en Ingeniería de Software y Sistemas Informáticos fue de 8.68.",
        "Jorge completó su Máster con un promedio de 8.68.",
        "El promedio final de Jorge en su Máster fue de 8.68 sobre 10.",
        "Jorge obtuvo una calificación promedio de 8.68 durante su Máster.",
        "En sus estudios de posgrado, Jorge alcanzó un promedio de 8.68.",
        "Su promedio en el Máster en Ingeniería de Software y Sistemas Informáticos fue de 8.68.",
        "Jorge terminó su formación de posgrado con un promedio de 8.68.",
        "La calificación promedio registrada de Jorge en el Máster es de 8.68 sobre 10.",
    ],
},

{
    category: "notas",
    keywords: [
        "promedio",
        "notas",
        "nota",
        "calificacion",
        "calificaciones",
        "notas academicas",
        "promedios",
        "promedio academico",
        "notas de jorge",
        "promedio de jorge",
    ],
    responses: [
        "Jorge obtuvo un promedio de 9 en Ingeniería en Sistemas y un promedio de 8.68 en el Máster en Ingeniería de Software y Sistemas Informáticos.",
        "En su formación universitaria, Jorge obtuvo un 9 de promedio en Ingeniería en Sistemas y 8.68 en el Máster.",
        "Sus promedios registrados son 9 en Ingeniería en Sistemas y 8.68 en el Máster en Ingeniería de Software y Sistemas Informáticos.",
        "Jorge obtuvo excelentes resultados académicos: 9 en su Ingeniería en Sistemas y 8.68 en su Máster.",
        "En total, Jorge cuenta con un promedio de 9 en su Ingeniería y 8.68 en su Máster.",
        "Sus notas académicas son 9 sobre 10 en Ingeniería en Sistemas y 8.68 sobre 10 en el Máster.",
        "Jorge obtuvo 9 de promedio durante su Ingeniería y 8.68 durante su formación de posgrado.",
        "En Ingeniería en Sistemas obtuvo 9 de promedio, mientras que en el Máster obtuvo 8.68.",
        "Los promedios académicos de Jorge son 9 en Ingeniería en Sistemas y 8.68 en Ingeniería de Software y Sistemas Informáticos.",
        "Jorge tuvo un promedio final de 9 en su carrera universitaria y de 8.68 en su Máster.",
    ],
},

    {
        category: "tecnologias",
        keywords: [
    "frontend",
    "front end",
    "front-end",
    "front",
    "desarrollo frontend",
    "desarrollo front end",
    "desarrollo front-end",
    "parte frontend",
    "parte front end",
    "frontend de jorge",
    "tecnologias frontend",
    "tecnologias de frontend",
    "tecnologias del frontend",
    "que usa en frontend",
    "que utiliza en frontend",
    "que tecnologias usa en frontend",
    "que tecnologias utiliza en frontend",
],
        responses: [
    "En frontend, Jorge trabaja principalmente con React y JavaScript.",

    "Para el desarrollo frontend, Jorge utiliza principalmente React y JavaScript.",

    "Jorge tiene experiencia en desarrollo frontend utilizando React y JavaScript.",

    "En la parte frontend de sus proyectos, Jorge trabaja con React y JavaScript.",

    "Jorge desarrolla interfaces web utilizando React y JavaScript.",

    "Su experiencia en frontend se centra principalmente en React y JavaScript.",

    "Para construir interfaces y aplicaciones web, Jorge utiliza React junto con JavaScript.",

    "Jorge trabaja en el desarrollo de la parte visual de las aplicaciones utilizando React y JavaScript.",

    "Dentro de sus tecnologías frontend, Jorge utiliza principalmente React y JavaScript.",

    "En el área de frontend, Jorge cuenta con experiencia trabajando con React y JavaScript."
],
    },

    {
        category: "tecnologias",
        keywords: [
    "backend",
    "back end",
    "back-end",
    "back",
    "desarrollo backend",
    "desarrollo back end",
    "desarrollo back-end",
    "parte backend",
    "parte back end",
    "backend de jorge",
    "tecnologias backend",
    "tecnologias de backend",
    "tecnologias del backend",
    "que usa en backend",
    "que utiliza en backend",
    "que tecnologias usa en backend",
    "que tecnologias utiliza en backend",
],
        responses: [
    "En backend, Jorge trabaja principalmente con Django y Java.",

    "Para el desarrollo backend, Jorge utiliza principalmente Django y Java.",

    "Jorge cuenta con experiencia en desarrollo backend utilizando Django y Java.",

    "En el lado del servidor, Jorge trabaja principalmente con Django y Java.",

    "Jorge desarrolla la parte backend de sus aplicaciones utilizando Django y Java.",

    "Su experiencia en backend se centra principalmente en Django y Java.",

    "Para construir la lógica del servidor, Jorge utiliza principalmente Django y Java.",

    "Jorge trabaja en el desarrollo del backend utilizando tecnologías como Django y Java.",

    "Dentro de sus tecnologías backend, Jorge utiliza principalmente Django y Java.",

    "En el área de backend, Jorge tiene experiencia trabajando con Django y Java."
],
    },

    {
        category: "tecnologias",
        keywords: [
    "base de datos",
    "bases de datos",
    "base de datos de jorge",
    "bases de datos de jorge",
    "bases de datos que usa",
    "bases de datos que utiliza",
    "que base de datos usa",
    "que bases de datos usa",
    "que base de datos utiliza",
    "que bases de datos utiliza",
    "tecnologias de base de datos",
    "tecnologias de bases de datos",
    "sistemas de bases de datos",
    "gestores de bases de datos",
],
        responses: [
    "Jorge trabaja con PostgreSQL y MySQL.",
    "En bases de datos, Jorge utiliza principalmente PostgreSQL y MySQL.",
    "Jorge tiene experiencia trabajando con PostgreSQL y MySQL.",
    "Entre las tecnologías de bases de datos que utiliza Jorge están PostgreSQL y MySQL.",
    "Jorge utiliza PostgreSQL y MySQL para gestionar los datos de sus aplicaciones.",
    "En el área de bases de datos, Jorge trabaja principalmente con PostgreSQL y MySQL.",
    "Su experiencia en bases de datos incluye el uso de PostgreSQL y MySQL.",
    "Jorge cuenta con experiencia utilizando PostgreSQL y MySQL en sus proyectos de software.",
    "Para la gestión y almacenamiento de datos, Jorge utiliza PostgreSQL y MySQL.",
    "Las principales bases de datos que utiliza Jorge son PostgreSQL
